[package]
name = "affogato_math"
version = "0.1.0"
edition = "2024"

[dependencies]
paste = "1.0.15"
rand = { version = "0.8.5", optional = true }
rand_pcg = { version = "0.3.1", optional = true }
[features]
rand = ["dep:rand"]
